name: Run benchmarks

on:
  pull_request:

jobs:
  Benchmark:
    runs-on: ubuntu-latest
    env:
      JULIA_DEBUG: BenchmarkCI
      # Add project root directory `.` to the load path:
      JULIA_LOAD_PATH: '@:.:'
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.4
      - run: julia -e "using Pkg; Pkg.instantiate()"
      - name: Run benchmarks
        run: julia -e "using BenchmarkCI; BenchmarkCI.judge()"
      - name: Post results
        run: julia -e "using BenchmarkCI; BenchmarkCI.postjudge()"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push results
        run: julia -e "using BenchmarkCI; BenchmarkCI.pushresult()"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - name: Push results (BenchmarkCI-data)
        run: julia -e '
          using BenchmarkCI;
          BenchmarkCI.pushresult(;
              url = "git@github.com:tkf/BenchmarkCI-data.git",
              title = "Benchmark result (BenchmarkCI-data)",
          );
          '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_KEY: ${{ secrets.ARTIFACTS_SSH_KEY }}
